
class CropOpts():
    CAN_BYPRODUCT_HARVEST = 'STROH'
    CAN_FERTILIZER_APLICATION= 'DUNG'
    CAN_COVERCROP_BEFORE = 'ZW_VOR'
    CAN_COVERCROP_AFTER = 'ZW_NACH'
    CAN_UNDERSAWN_AFTER = 'US_NACH'
    
    
    
    